### ISSUE TITLE
Blazor templates outdated

### ISSUE THREAD

**Issue by Awide** [vikramlearning/blazorbootstrap-starter-templates#10]
I believe from .NET 8.0 (although at least from the current version) the file templates were updated to a different structure. There is no more index.html and for client and server sided rendering two folders are generated instead of only one.

**Comment by gvreddy04** [comment]
@Awide Thank you for trying **BlazorBootstrap**. Are you looking for the starter template below?

Link: https://github.com/vikramlearning/blazorbootstrap-starter-templates/tree/master/src/BlazorBootstrap.Templates.Starter/Net8.BlazorAutoGlobal.

If not, please specify which template is outdated. We will revisit it.

Your feedback is appreciated.

**Comment by gvreddy04** [comment]
@Awide Screenshot for your reference.

![image](https://github.com/vikramlearning/blazorbootstrap-starter-templates/assets/2337067/7ca8eef6-f625-4c8e-9a3c-89974671f59a)
