### ISSUE TITLE
Exception Message is always shown

### ISSUE THREAD

**Issue by mdeppe42** [vikramlearning/blazorbootstrap-starter-templates#4]
On startup of the NET6.BlazorServerApp project, the exception warning "An unhandled exception has occurred. See browser dev tools for details." is shown at the bottom of the page. I need to scroll down do have it visible. I believe there is no exception, at least there is none shown in VS or browser console.

How to get this working? One could remove the `<div id="blazor-error-ui">` from _Layout.cshtml, but then there would be no exception notification at all.

**Comment by gvreddy04** [comment]
@mdeppe42 I'll take a look at this. But I'll recommend using the Visual Studio Templates.
Link: https://github.com/vikramlearning/blazorbootstrap-project-templates#blazor-bootstrap-templates

**Note:** Once the new project is created, upgrade the BlazorBootstrap package version to the latest version available.

**Comment by KevynSB** [comment]
I have the same problem

**Comment by gvreddy04** [comment]
@mdeppe42 @KevynSB Unfortunately, I'm not able to replicate the issue. Please see the following screenshot foe reference.

![image](https://github.com/vikramlearning/blazorbootstrap-starter-templates/assets/2337067/ea5db4fe-822a-4d8f-8a0f-c94f0e42889a)

If possible can you record your screen and share the video here.

**Comment by mdeppe42** [comment]
On your screenshot the scrollbar is not at the bottom, I think the warning is displayed when you scroll down.

**Comment by mdeppe42** [comment]
<img width="921" alt="screen" src="https://github.com/vikramlearning/blazorbootstrap-starter-templates/assets/99365523/6960c9fd-78a9-48b6-bf8e-02b560a24390">
