### ISSUE TITLE
Border around page heading

### ISSUE THREAD

**Issue by mdeppe42** [vikramlearning/blazorbootstrap-starter-templates#5]
On startup of the Demo Apps (Server and WebAssembly) the "Hello, World" heading appears with a border, as if it was selected using the tab key. It occurs in Firefox and Edge.
How can I avoid this?

<img width="945" alt="helloworld" src="https://github.com/vikramlearning/blazorbootstrap-starter-templates/assets/99365523/44cc700e-6e70-4b33-aac0-89df7e5791ab">

**Comment by gvreddy04** [comment]
https://github.com/vikramlearning/blazorbootstrap-starter-templates/blob/master/src/BlazorBootstrap.Templates.Starter/NET6.BlazorServerApp/App.razor

Comment the below line in **App.razor** page:
```html
<FocusOnNavigate RouteData="@routeData" Selector="h1" />
```
