### ISSUE TITLE
Issues setting up the .NET 8 starter template

### ISSUE THREAD

**Issue by birger-ant** [vikramlearning/blazorbootstrap-starter-templates#8]
Hi there

When running the NET8.BlazorWebAppRenderModeServerGlobal it the following error

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateStaticWebAsssetsPropsFile" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Birger\Source\Repos\blazorbootstrap-starter-templates\src\BlazorBootstrap.Templates.Starter\NET8.BlazorWebAppRenderModeServerGlobal\obj\Debug\net8.0\staticwebassets\msbuild.NET8.BlazorWebAppRenderModeServerGlobal.Microsoft.AspNetCore.StaticWebAssets.props'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAsssetsPropsFile.ExecuteCore()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	NET8.BlazorWebAppRenderModeServerGlobal	C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Pack.targets	136	
![screenshot-error-blazor8-blazorbootstrap](https://github.com/vikramlearning/blazorbootstrap-starter-templates/assets/77225692/a9ed728a-aeca-4827-b312-f72fa1bb1507)

When following the startup guide here instead

https://docs.blazorbootstrap.com/getting-started/blazor-webapp-server-global-net-8 

I get an error in the developer console

Failed to load resource: the server responded with a status of 404 () https://localhost:7066/NET8.BlazorWebAppRenderModeServerGlobal.styles.css

**Comment by gvreddy04** [comment]
@birger-ant, thank you for trying BlazorBootstrap. I've understood your error.

![image](https://github.com/vikramlearning/blazorbootstrap-starter-templates/assets/2337067/5be58aae-24ce-483f-a2f2-9b218a750d80)

In the above screenshot, the highlighted line is generated as part of the starter project. Please do not copy that line to your page. The default CSS file will be similar to your project file name. Just keep the default generated reference as is.

**Comment by gvreddy04** [comment]
> Hi there
> 
> When running the NET8.BlazorWebAppRenderModeServerGlobal it the following error
> 
> Severity Code Description Project File Line Suppression State Error MSB4018 The "GenerateStaticWebAsssetsPropsFile" task failed unexpectedly. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Birger\Source\Repos\blazorbootstrap-starter-templates\src\BlazorBootstrap.Templates.Starter\NET8.BlazorWebAppRenderModeServerGlobal\obj\Debug\net8.0\staticwebassets\msbuild.NET8.BlazorWebAppRenderModeServerGlobal.Microsoft.AspNetCore.StaticWebAssets.props'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost) at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAsssetsPropsFile.ExecuteCore() at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext() NET8.BlazorWebAppRenderModeServerGlobal C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Pack.targets 136 ![screenshot-error-blazor8-blazorbootstrap](https://private-user-images.githubusercontent.com/77225692/293449869-a9ed728a-aeca-4827-b312-f72fa1bb1507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNDY0NjMsIm5iZiI6MTcwNDA0NjE2MywicGF0aCI6Ii83NzIyNTY5Mi8yOTM0NDk4NjktYTllZDcyOGEtYWVjYS00ODI3LWIzMTItZjcyZmExYmIxNTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE4MDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MjYxNTFlMjFiZWRlNjA4MjMwYjk4ZDllNjIyNDIxMzU3YmI0ZTUzZGE3MzA5ODI2NzQzN2Y1OWFiN2M1ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rYxSX0zzv_eksEZRoh3oJSqDuO_53rpOCWSFkfPVyN8)
> 

For this issue, please clean the solution and rebuild. Let me know, if you need further help.
