### ISSUE TITLE
Could not find window.blazorBootsrap.collapse.initialize ('blazorBootsrap' was undefined)

### ISSUE THREAD

**Issue by alexnayberg** [vikramlearning/blazorbootstrap-starter-templates#9]
Hello,
I just installed BlazorBootstrap on a Blazor Web App project on .Net 8. I am having a problem with a component that's using Accordion. This is the error I am seeing:

>  Error: Microsoft.JSInterop.JSException: Could not find 'window.blazorBootstrap.collapse.initialize' ('blazorBootstrap' was undefined).
>  Error: Could not find 'window.blazorBootstrap.collapse.initialize' ('blazorBootstrap' was undefined).
>     at https://localhost:7281/_framework/blazor.web.js:1:734
>     at Array.forEach (<anonymous>)
>     at l.findFunction (https://localhost:7281/_framework/blazor.web.js:1:702)
>     at b (https://localhost:7281/_framework/blazor.web.js:1:5445)
>     at https://localhost:7281/_framework/blazor.web.js:1:3238
>     at new Promise (<anonymous>)
>     at y.beginInvokeJSFromDotNet (https://localhost:7281/_framework/blazor.web.js:1:3201)
>     at fn._invokeClientMethod (https://localhost:7281/_framework/blazor.web.js:1:62541)
>     at fn._processIncomingData (https://localhost:7281/_framework/blazor.web.js:1:60016)
>     at connection.onreceive (https://localhost:7281/_framework/blazor.web.js:1:53657)
>    at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
>    at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
>    at BlazorBootstrap.Collapse.<OnInitializedAsync>b__4_0()
>    at BlazorBootstrap.BlazorBootstrapComponentBase.OnAfterRenderAsync(Boolean firstRender)
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

   I tried it in both Server and WebAssembly projects, and got the error in both. I followed your instructions to make sure I didn't miss anything: [Getting Started](https://docs.blazorbootstrap.com/getting-started/blazor-webapp-auto-global-net-8).

**Comment by gvreddy04** [comment]
@alexnayberg, thank you for trying BlazorBootstrap. Please share a sample code or GitHub repo to reproduce the issue, rather than assuming. This will help us to better understand the issue.

**Comment by gvreddy04** [comment]
@alexnayberg Please test your changes in the below starter project and let me know.

Starter Project: https://github.com/vikramlearning/blazorbootstrap-starter-templates/tree/master/src/BlazorBootstrap.Templates.Starter/Net8.BlazorAutoGlobal

**Comment by gvreddy04** [comment]
@alexnayberg  Pleaseshare the below information:

 - BlazorBootstrap Version: 
 - Blazor WebAssembly / Server: 
 - Interactive RenderMode: 
 - Render Location: 
 - .NET Version: 

Also share a GitHub repo to reproduce your issue. I'll a take look and let you know what was missing.

**Comment by AdamBauerle** [comment]
We are also seeing this same issue on a newer .NET 9 Blazor Hybrid project. Here is the requested info from the previous post (that was not followed up on).

BlazorBootstrap Version: 3.3.1
Blazor WebAssembly / Server: Server
Interactive RenderMode: InteractiveServer
Render Location: MainLayout.razor
.NET Version: .NET 9

This package looks promising, but first go at it produces this same error on the latest .NET 9 fresh project standup.

Any help would be very appreciated. Thank you!

**Comment by markavg** [comment]
Seeing also the same issue on MAUI Blazor Hybrid Deployed to Android
BlazorBootstrap Version: 3.3.1
.NET 8

[chromium] [INFO:CONSOLE(90)] "Uncaught SyntaxError: Unexpected token .", source: https://0.0.0.0/_content/Blazor.Bootstrap/blazor.bootstrap.js (90)


Encountered on a Simple ToastService Call
@page "/counter"

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    [Inject] protected ToastService ToastService { get; set; } = default!;
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
        ToastService.Notify(new(ToastType.Success, $"Employee details saved successfully."));
    }
}

**Comment by markavg** [comment]
Seeing also the same issue on MAUI Blazor Hybrid Deployed to Android
BlazorBootstrap Version: 3.3.1
.NET 8

With error of

[chromium] [INFO:CONSOLE(90)] "Uncaught SyntaxError: Unexpected token .", source: https://0.0.0.0/_content/Blazor.Bootstrap/blazor.bootstrap.js (90)

 "Could not find 'window.blazorBootstrap.toasts.show' ('blazorBootstrap' was undefined).

**Comment by markavg** [comment]
Found the solution on my end.

I was trying to develop on Android via Emulator API lvl 29 when I encountered the error.
Solution for me was to update the Android SystemWebView via PlayStore and it now works.
